spring.application.name=picselB


#spring.datasource.name=picseldb
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/picseldb
#spring.datasource.username=root
#spring.datasource.password=root

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
frontend.url=${FRONTEND_URL}


#http://localhost:5173/



spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect








cloudinary.cloud_name=dawygcqzs
cloudinary.api_key=463654647176597
cloudinary.api_secret=oxPjujAxD8wuIGdpxkXcHzzX-Is
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB
server.tomcat.max-http-form-post-size=30MB